import type { Metadata } from 'next';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { ApiTester } from '@/components/ApiTester';
import { Terminal, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
export const metadata: Metadata = {title:'API y actualizaciones para desarrolladores',description:'Consulta versiones, prueba la API de actualizaciones y revisa los endpoints de Proton Apps.',alternates:{canonical:'https://protondev.space/apps/developers'}};
export default function DevelopersPage() {
  return <><Navbar /><main id="main-content" className="site-container py-12 sm:py-16"><Link href="/" className="inline-flex gap-2 items-center text-sm text-slate-400 hover:text-white"><ArrowLeft size={16} aria-hidden="true" /> Volver a Proton Apps</Link><p className="eyebrow mt-10 flex items-center gap-2"><Terminal size={16} aria-hidden="true" /> Para desarrolladores</p><h1 className="mt-4 text-4xl sm:text-5xl font-semibold tracking-tight">Versiones claras.<br />Actualizaciones conectadas.</h1><p className="mt-5 max-w-2xl text-slate-400 leading-relaxed">Consulta la versión disponible para cada aplicación. La API indica si existe una actualización y si el lanzamiento está marcado como crítico. Tu aplicación decide cómo presentar esa información.</p><div className="mt-10 panel p-5 sm:p-8"><ApiTester initialSlug="finup" /></div><section className="mt-12"><h2 className="text-2xl font-semibold">Endpoints públicos</h2><div className="grid gap-4 mt-5 sm:grid-cols-2">{[['/apps/api/v1/apps','Catálogo y versiones disponibles.'],['/apps/api/v1/apps/:slug/updates','Comprueba una actualización con version_code y platform.'],['/apps/api/v1/download/:releaseId','Descarga el archivo de una versión.']].map(([endpoint,description]) => <div key={endpoint} className="panel p-5"><code className="text-sm text-cyan-300 break-all">GET {endpoint}</code><p className="mt-3 text-sm text-slate-400">{description}</p></div>)}</div></section></main><Footer /></>;
}
